name: Build and Release

on:
  push:
    branches: [ main ]
    tags: [ 'v*' ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    
    strategy:
      matrix:
        platform: [x64, x86, ARM64]
        configuration: [Release]

    steps:
    - uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.3

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration ${{ matrix.configuration }} --no-restore

    - name: Publish
      run: dotnet publish --configuration ${{ matrix.configuration }} --runtime win10-${{ matrix.platform }} --self-contained true --output ./publish/${{ matrix.platform }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: MiniKeyboard-${{ matrix.platform }}
        path: ./publish/${{ matrix.platform }}

  release:
    needs: build
    runs-on: windows-latest
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          MiniKeyboard-x64/**
          MiniKeyboard-x86/**  
          MiniKeyboard-ARM64/**
        draft: false
        prerelease: false
      env:

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
